### ISSUE TITLE
jasmine-unit fails in example because of error in dependency

### ISSUE THREAD

**Issue by sclausen** [xolvio/jasmine-unit#21]
I don't know if this is an issue for jasmine-unit, or jasmine-node-reporter-fix.

I used meteor 0.8.2

smart.lock:

```
{
  "meteor": {},
  "dependencies": {
    "basePackages": {
      "velocity": {},
      "mocha-web-velocity": {},
      "jasmine-unit": {},
      "velocity-html-reporter": {},
      "moment": {}
    },
    "packages": {
      "velocity": {
        "git": "https://github.com/xolvio/velocity.git",
        "tag": "v0.1.10",
        "commit": "b9f6291dd2453ac47773cadc72a9e94438ee9cdb"
      },
      "mocha-web-velocity": {
        "git": "https://github.com/mad-eye/meteor-mocha-web.git",
        "tag": "v0.3.0",
        "commit": "1204867efdb23ba6115157b5f2e68da4edb7d8e9"
      },
      "jasmine-unit": {
        "git": "https://github.com/xolvio/jasmine-unit.git",
        "tag": "v0.1.17",
        "commit": "d96a7e46ec5bcb3fdf8a3c8c0b75e084dc168c1b"
      },
      "velocity-html-reporter": {
        "git": "https://github.com/rdickert/velocity-html-reporter.git",
        "tag": "v0.1.3",
        "commit": "c7511d3741bacc75edb30c7c217696bfcffdbab4"
      },
      "moment": {
        "git": "https://github.com/acreeger/meteor-moment.git",
        "tag": "v2.6.0",
        "commit": "26156df681750fd6e6ed77043eef32b6653ebbdf"
      },
      "mirror": {
        "git": "https://github.com/xdissent/meteor-mirror.git",
        "tag": "v0.0.2",
        "commit": "03d965dcab2f976a1fdc6ce513edcd4c17b75746"
      },
      "package-stubber": {
        "git": "https://github.com/alanning/meteor-package-stubber.git",
        "tag": "v0.0.7",
        "commit": "f6d76ae3c9107d25e42bc5b297a8799145e99f73"
      }
    }
  }
}
```

console:

```
I20140703-07:29:23.034(2)? Velocity Jasmine-Unit is loaded
=> Started your app.

=> App running at: http://localhost:3000/
I20140703-07:29:25.241(2)? /home/sebastian/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/d96a7e46ec5bcb3fdf8a3c8c0b75e084dc168c1b/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/reporter.js:336
I20140703-07:29:25.241(2)? /home/sebastian/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/d96a7e46ec5bcb3fdf8a3c8c0b75e084dc168c1b/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/reporter.js:336
I20140703-07:29:25.241(2)?   jasmineNode.TeamcityReporter.prototype = new jasmine.TeamcityReporter;
I20140703-07:29:25.241(2)?                                            ^
I20140703-07:29:25.241(2)? TypeError: undefined is not a function
I20140703-07:29:25.241(2)?     at /home/sebastian/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/d96a7e46ec5bcb3fdf8a3c8c0b75e084dc168c1b/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/reporter.js:336:44
I20140703-07:29:25.241(2)?     at Object.<anonymous> (/home/sebastian/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/d96a7e46ec5bcb3fdf8a3c8c0b75e084dc168c1b/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/reporter.js:342:3)
I20140703-07:29:25.242(2)?     at Module._compile (module.js:456:26)
I20140703-07:29:25.242(2)?     at Object.Module._extensions..js (module.js:474:10)
I20140703-07:29:25.242(2)?     at Module.load (module.js:356:32)
I20140703-07:29:25.242(2)?     at Function.Module._load (module.js:312:12)
I20140703-07:29:25.242(2)?     at Module.require (module.js:364:17)
I20140703-07:29:25.242(2)?     at require (module.js:380:17)
I20140703-07:29:25.242(2)?     at Object.<anonymous> (/home/sebastian/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/d96a7e46ec5bcb3fdf8a3c8c0b75e084dc168c1b/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/index.js:39:21)
I20140703-07:29:25.242(2)?     at Module._compile (module.js:456:26)
I20140703-07:29:25.243(2)? All done executing rsync -avq --rsh="ssh" --delete --delay-updates --force --exclude=".meteor/local" --exclude="tests/.*" /home/sebastian/projects/velocity/example/ /home/sebastian/projects/velocity/example/.meteor/local/.mirror
I20140703-07:29:25.243(2)? rsync took 1192
I20140703-07:29:25.243(2)? Starting mirror on port 5000
```

**Comment by PlugIN73** [comment]
I have the same problem! :(

**Comment by alanning** [comment]
Hi @sclausen, @PlugIN73,

Could one of you put a repro up on Github please?  I'd like to figure this out but am having trouble reproducing it on my test boxes.

Also, what OS's are you guys running?

**Comment by queso** [comment]
@alanning I have one, I hit the same error last night when doing an AirPair on meteor.

You can see the basic repo here: https://github.com/queso/chatApp.

**Comment by alanning** [comment]
Ok, i think this is an issue with the version of jasmine-node that I forked to make jasmine-node-reporter-fix.  [This SO answer](http://stackoverflow.com/a/24555340/219238) says reverting to jasmine-node v1.14.2 resolves this so I'll revert my jasmine-node-reporter-fix to 1.14.2 and re-release.

Issue is being tracked on the jasmine-reporters repo:  
https://github.com/larrymyers/jasmine-reporters/issues/63

I commented with my guess as to why its happening here:
https://github.com/larrymyers/jasmine-reporters/issues/63#issuecomment-47933615

**Comment by alanning** [comment]
... there is no v1.14.2 tag to revert to.  That repo goes from v1.14.1 to v1.14.3...

Will work with Josh's chatApp to try to resolve the underlying problem.

**Comment by marcodejongh** [comment]
@alanning revert to branch Jasmine1.3 which is tagged v1.14.1. according to the history.md v1.14.2 was a mistake. I tried it on my own fork but for some reason Npm.depends in node-unit does not except a tarball link

**Comment by alanning** [comment]
jasmine-unit v0.1.18 pushed to atmosphere with a fix for this.  

Tested with @queso 's chatApp repo.

It uses an updated fork of jasmine-node, [jasmine-node-reporter-fix](https://www.npmjs.org/package/jasmine-node-reporter-fix), which fixes the TeamcityReporter error.
