### ISSUE TITLE
Cannot set property 'rendered' of undefined

### ISSUE THREAD

**Issue by alanning** [xolvio/jasmine-unit#25]
'[from velocity-core [post](https://groups.google.com/forum/#!topic/velocity-core/GKmp0WY3EGc)]

mocha-web-velocity does load the file correctly.

These are the packages:

```
standard-app-packages
autopublish
insecure
stylus
coffeescript
bootstrap
jade
velocity
mocha-web-velocity
jasmine-unit
```

Here's the log:

```
$ DEBUG=1 JASMINE_DEBUG=1 VELOCITY_DEBUG=1 mrt

Stand back while Meteorite does its thing

Done installing smart packages

Ok, everything's ready. Here comes Meteor!

[[[[[ ~/Dropbox/viewmodel ]]]]]

=> Started proxy.
=> Started MongoDB.     
I20140712-08:56:32.010(-6)? PWD /home/manuel/Dropbox/viewmodel
I20140712-08:56:32.147(-6)? Check for test package configs... [ 'packages/jade/smart.json',
I20140712-08:56:32.148(-6)?   'packages/jasmine-unit/smart.json',
I20140712-08:56:32.148(-6)?   'packages/mirror/example/smart.json',
I20140712-08:56:32.150(-6)?   'packages/mirror/smart.json',
I20140712-08:56:32.150(-6)?   'packages/mocha-web-velocity/smart.json',
I20140712-08:56:32.151(-6)?   'packages/package-stubber/example-app/smart.json',
I20140712-08:56:32.151(-6)?   'packages/package-stubber/smart.json',
I20140712-08:56:32.152(-6)?   'packages/velocity/example/smart.json',
I20140712-08:56:32.152(-6)?   'packages/velocity/smart.json' ]
I20140712-08:56:32.153(-6)? velocity config = {
I20140712-08:56:32.153(-6)?   "jasmine-unit": {
I20140712-08:56:32.154(-6)?     "name": "jasmine-unit",
I20140712-08:56:32.154(-6)?     "description": "Velocity-compatible unit test package with jasmine syntax",
I20140712-08:56:32.155(-6)?     "homepage": "https://github.com/xolvio/jasmine-unit",
I20140712-08:56:32.155(-6)?     "author": "Sam Hatoum",
I20140712-08:56:32.156(-6)?     "version": "0.1.22",
I20140712-08:56:32.156(-6)?     "git": "https://github.com/xolvio/jasmine-unit.git",
I20140712-08:56:32.156(-6)?     "testPackage": true,
I20140712-08:56:32.157(-6)?     "regex": "-jasmine-unit.(js|coffee)$",
I20140712-08:56:32.157(-6)?     "packages": {
I20140712-08:56:32.158(-6)?       "velocity": "",
I20140712-08:56:32.159(-6)?       "package-stubber": ""
I20140712-08:56:32.159(-6)?     },
I20140712-08:56:32.160(-6)?     "_regexp": {}
I20140712-08:56:32.160(-6)?   },
I20140712-08:56:32.160(-6)?   "mocha-web-velocity": {
I20140712-08:56:32.161(-6)?     "name": "mocha-web-velocity",
I20140712-08:56:32.161(-6)?     "description": "Easily and securely use mocha within client side Meteor",
I20140712-08:56:32.162(-6)?     "homepage": "https://github.com/mad-eye/meteor-mocha-web",
I20140712-08:56:32.162(-6)?     "author": "Madeye  (http://madeye.io)",
I20140712-08:56:32.163(-6)?     "version": "0.3.3",
I20140712-08:56:32.163(-6)?     "git": "https://github.com/mad-eye/meteor-mocha-web.git",
I20140712-08:56:32.164(-6)?     "testPackage": true,
I20140712-08:56:32.165(-6)?     "regex": "(-mocha-web-velocity.(js|coffee)$)|(tests/mocha-web-velocity/)",
I20140712-08:56:32.165(-6)?     "packages": {
I20140712-08:56:32.166(-6)?       "mirror": "0.0.2"
I20140712-08:56:32.167(-6)?     },
I20140712-08:56:32.167(-6)?     "_regexp": {}
I20140712-08:56:32.167(-6)?   }
I20140712-08:56:32.168(-6)? }
I20140712-08:56:32.552(-6)? All done executing rsync -avq --rsh="ssh" --delete --delay-updates --force --exclude=".meteor/local" --exclude="tests/.*" /home/manuel/Dropbox/viewmodel/ /home/manuel/Dropbox/viewmodel/.meteor/local/.mirror
I20140712-08:56:32.553(-6)? rsync took 601
I20140712-08:56:32.558(-6)? Jasmine-Unit is loaded
I20140712-08:56:32.573(-6)? Starting mirror on port 5000
=> Started your app.

=> App running at: http://localhost:3000/
I20140712-08:56:32.708(-6)? File added: /home/manuel/Dropbox/viewmodel/tests/a1-package-stubs.js
I20140712-08:56:32.709(-6)? File added: /home/manuel/Dropbox/viewmodel/tests/viewmodel-jasmine-unit.coffee
I20140712-08:56:32.711(-6)? jasmine-unit  <=  /home/manuel/Dropbox/viewmodel/tests/viewmodel-jasmine-unit.coffee
I20140712-08:56:32.754(-6)? File added: /home/manuel/Dropbox/viewmodel/tests/mocha-web-velocity/client/viewmodel.coffee
I20140712-08:56:32.755(-6)? mocha-web-velocity  <=  /home/manuel/Dropbox/viewmodel/tests/mocha-web-velocity/client/viewmodel.coffee
I20140712-08:56:32.757(-6)? File added: /home/manuel/Dropbox/viewmodel/tests/mocha-web-velocity/server/server.js
I20140712-08:56:32.758(-6)? mocha-web-velocity  <=  /home/manuel/Dropbox/viewmodel/tests/mocha-web-velocity/server/server.js
I20140712-08:56:32.975(-6)? [PackageStubber] custom stub found for core package jquery
I20140712-08:56:32.976(-6)? [PackageStubber] custom stub found for core package underscore
I20140712-08:56:33.046(-6)? [PackageStubber] ignoring jasmine-unit
I20140712-08:56:33.052(-6)? [PackageStubber] ignoring mirror
I20140712-08:56:33.055(-6)? [PackageStubber] ignoring mocha-web-velocity
I20140712-08:56:33.057(-6)? [PackageStubber] ignoring package-stubber
I20140712-08:56:33.067(-6)? [PackageStubber] ignoring velocity
I20140712-08:56:33.072(-6)? [PackageStubber] appending custom stub for package jquery
I20140712-08:56:33.076(-6)? [PackageStubber] appending custom stub for package underscore
I20140712-08:56:33.083(-6)? jasmine cli:  /home/manuel/.meteor/tools/858c88b520/bin/node /home/manuel/Dropbox/viewmodel/packages/jasmine-unit/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/cli.js --coffee --color --verbose --match .*-jasmine-unit. --matchall --junitreport --output /home/manuel/Dropbox/viewmodel/tests/.reports/jasmine-unit /home/manuel/Dropbox/viewmodel/packages/jasmine-unit/lib /home/manuel/Dropbox/viewmodel/tests
I20140712-08:56:33.084(-6)? File changed: /home/manuel/Dropbox/viewmodel/tests/a1-package-stubs.js
I20140712-08:56:33.738(-6)? stubbing template: player
I20140712-08:56:33.740(-6)? stubbing template: leaderboard
I20140712-08:56:33.742(-6)? stubbing template: hello
I20140712-08:56:33.756(-6)? stubbing template: mochaTestObject
I20140712-08:56:33.756(-6)? stubbing template: serverTestReport
I20140712-08:56:33.757(-6)? stubbing template: mochaTestReport
I20140712-08:56:33.757(-6)? stubbing template: mochaweb
I20140712-08:56:33.758(-6)? stubbing template: hello
I20140712-08:56:33.758(-6)? stubbing template: match-html-markdownFilter
I20140712-08:56:33.760(-6)? stubbing template: match-html-inclusionWithKeywordArgs
I20140712-08:56:33.762(-6)? stubbing template: match-html-inclusionWithPositionalArgs
I20140712-08:56:33.763(-6)? stubbing template: match-html-contentsInclusion
I20140712-08:56:33.763(-6)? stubbing template: match-html-inclusion
I20140712-08:56:33.763(-6)? stubbing template: match-html-elseif
I20140712-08:56:33.764(-6)? stubbing template: match-html-each
I20140712-08:56:33.765(-6)? stubbing template: match-html-with
I20140712-08:56:33.765(-6)? stubbing template: match-html-ifAndElse
I20140712-08:56:33.766(-6)? stubbing template: match-html-if
I20140712-08:56:33.766(-6)? stubbing template: match-html-tagAttributeInterpolation
I20140712-08:56:33.767(-6)? stubbing template: match-html-multipleInlineHelpers
I20140712-08:56:33.767(-6)? stubbing template: match-html-mustacheCall
I20140712-08:56:33.767(-6)? stubbing template: match-html-unescapedInlineHelper
I20140712-08:56:33.767(-6)? stubbing template: match-html-inlineHelper
I20140712-08:56:33.768(-6)? stubbing template: match-html-justHelper
I20140712-08:56:33.768(-6)? stubbing template: match-html-tagHelper
I20140712-08:56:33.769(-6)? stubbing template: match-html-multipleChildren
I20140712-08:56:33.785(-6)? stubbing template: match-html-justText
I20140712-08:56:33.786(-6)? stubbing template: match-html-iframe
I20140712-08:56:33.789(-6)? stubbing template: match-html-inlineBracketsTags
I20140712-08:56:33.790(-6)? stubbing template: match-html-inlineColonTags
I20140712-08:56:33.792(-6)? stubbing template: match-html-cssClasses
I20140712-08:56:33.792(-6)? stubbing template: match-html-multipleTagAttributes
I20140712-08:56:33.793(-6)? stubbing template: match-html-dynamicTagAttributes
I20140712-08:56:33.793(-6)? stubbing template: match-html-helperInTagAttribute
I20140712-08:56:33.794(-6)? stubbing template: match-html-tagAttributeWithTextValue
I20140712-08:56:33.794(-6)? stubbing template: match-html-singleTagAttribute
I20140712-08:56:33.795(-6)? loading stub file: a1-package-stubs.js
I20140712-08:56:33.996(-6)? loading source file: /home/manuel/Dropbox/viewmodel/client/lib/ViewModel.coffee
I20140712-08:56:34.314(-6)? loading source file: /home/manuel/Dropbox/viewmodel/client/lib/ViewModel.js
I20140712-08:56:34.318(-6)? loading source file: /home/manuel/Dropbox/viewmodel/client/lib/parseBind.js
I20140712-08:56:34.323(-6)? loading source file: /home/manuel/Dropbox/viewmodel/lib/Global.coffee
I20140712-08:56:34.339(-6)? loading source file: /home/manuel/Dropbox/viewmodel/lib/collections.coffee
I20140712-08:56:34.346(-6)? loading source file: /home/manuel/Dropbox/viewmodel/client/tutorial/attr/attr.coffee
I20140712-08:56:34.357(-6)? Error loading app files Cannot set property 'rendered' of undefined TypeError: Cannot set property 'rendered' of undefined
I20140712-08:56:34.358(-6)?   at evalmachine.<anonymous>:1:24
I20140712-08:56:34.359(-6)?   at /home/manuel/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/7046cb7a9c745dc6e3c915962ed8876a48229739/lib/coffee-require.js:69:16
I20140712-08:56:34.359(-6)?   at coffeePreprocessor (/home/manuel/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/7046cb7a9c745dc6e3c915962ed8876a48229739/lib/coffee-require.js:50:9)
I20140712-08:56:34.360(-6)?   at module.exports (/home/manuel/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/7046cb7a9c745dc6e3c915962ed8876a48229739/lib/coffee-require.js:64:5)
I20140712-08:56:34.360(-6)?   at loadFile (/home/manuel/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/7046cb7a9c745dc6e3c915962ed8876a48229739/lib/file-loader.js:108:7)
I20140712-08:56:34.361(-6)?   at Function.forEach (/home/manuel/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/7046cb7a9c745dc6e3c915962ed8876a48229739/.npm/package/node_modules/lodash/dist/lodash.js:3297:15)
I20140712-08:56:34.362(-6)?   at Object.loadFiles (/home/manuel/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/7046cb7a9c745dc6e3c915962ed8876a48229739/lib/file-loader.js:34:5)
I20140712-08:56:34.373(-6)?   at Object.<anonymous> (/home/manuel/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/7046cb7a9c745dc6e3c915962ed8876a48229739/lib/loader-helper.js:43:14)
I20140712-08:56:34.374(-6)?   at Module._compile (module.js:456:26)
I20140712-08:56:34.375(-6)?   at Object.Module._extensions..js (module.js:474:10)
I20140712-08:56:34.375(-6)?   at Module.load (/home/manuel/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/7046cb7a9c745dc6e3c915962ed8876a48229739/.npm/package/node_modules/jasmine-node-reporter-fix/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
I20140712-08:56:34.376(-6)?   at Function.Module._load (module.js:312:12)
I20140712-08:56:34.376(-6)?   at Module.require (module.js:364:17)
I20140712-08:56:34.378(-6)?   at require (module.js:380:17)
I20140712-08:56:34.379(-6)?   at Object.jasmine.loadHelpersInFolder (/home/manuel/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/7046cb7a9c745dc6e3c915962ed8876a48229739/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/index.js:64:20)
I20140712-08:56:34.379(-6)?   at /home/manuel/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/7046cb7a9c745dc6e3c915962ed8876a48229739/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/cli.js:221:13
I20140712-08:56:34.380(-6)?   at Array.forEach (native)
I20140712-08:56:34.382(-6)?   at Object.<anonymous> (/home/manuel/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/7046cb7a9c745dc6e3c915962ed8876a48229739/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/cli.js:220:15)
I20140712-08:56:34.382(-6)?   at Module._compile (module.js:456:26)
I20140712-08:56:34.383(-6)?   at Object.Module._extensions..js (module.js:474:10)
I20140712-08:56:34.393(-6)?   at Module.load (module.js:356:32)
I20140712-08:56:34.394(-6)?   at Function.Module._load (module.js:312:12)
I20140712-08:56:34.394(-6)?   at Function.Module.runMain (module.js:497:10)
I20140712-08:56:34.395(-6)?   at startup (node.js:119:16)
I20140712-08:56:34.397(-6)?   at node.js:906:3
I20140712-08:56:34.413(-6)? 
I20140712-08:56:34.414(-6)? creating junit xml report save path: /home/manuel/Dropbox/viewmodel/tests/.reports/jasmine-unit
I20140712-08:56:34.415(-6)? patched JUnitXmlReporter.writeFile
I20140712-08:56:34.482(-6)? 
I20140712-08:56:34.483(-6)? ViewModel - 24 ms
I20140712-08:56:34.484(-6)?     should create - 22 ms
I20140712-08:56:34.520(-6)? 
I20140712-08:56:34.531(-6)? Failures:
I20140712-08:56:34.535(-6)? 
I20140712-08:56:34.539(-6)?   1) ViewModel should create
I20140712-08:56:34.540(-6)?    Message:
I20140712-08:56:34.540(-6)?      TypeError: undefined is not a function
I20140712-08:56:34.548(-6)?    Stacktrace:
I20140712-08:56:34.550(-6)?      TypeError: undefined is not a function
I20140712-08:56:34.551(-6)?   at [object Object].<anonymous> (/home/manuel/Dropbox/viewmodel/tests/viewmodel-jasmine-unit.coffee:4:14)
I20140712-08:56:34.552(-6)?   at Object.jasmine.executeSpecsInFolder (/home/manuel/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/7046cb7a9c745dc6e3c915962ed8876a48229739/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/index.js:186:16)
I20140712-08:56:34.569(-6)?   at Object.<anonymous> (/home/manuel/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/7046cb7a9c745dc6e3c915962ed8876a48229739/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/cli.js:248:9)
I20140712-08:56:34.575(-6)?   at Module._compile (module.js:456:26)
I20140712-08:56:34.606(-6)?   at Object.Module._extensions..js (module.js:474:10)
I20140712-08:56:34.627(-6)?   at Module.load (module.js:356:32)
I20140712-08:56:34.631(-6)?   at Function.Module._load (module.js:312:12)
I20140712-08:56:34.642(-6)?   at Function.Module.runMain (module.js:497:10)
I20140712-08:56:34.643(-6)?   at startup (node.js:119:16)
I20140712-08:56:34.643(-6)?   at node.js:906:3
I20140712-08:56:34.643(-6)? 
I20140712-08:56:34.644(-6)? 
I20140712-08:56:34.644(-6)? Finished in 0.032 seconds
I20140712-08:56:34.645(-6)? 1 test, 1 assertion, 1 failure, 0 skipped
I20140712-08:56:34.645(-6)? 
I20140712-08:56:34.646(-6)? 
```

**Comment by alanning** [comment]
This is most likely due to a missing stub.  Looks like something in the `attr.coffee` file is expecting to find an object with a `rendered` property but that object doesn't exist when run outside the Meteor context.  If you stub that object it should fix this issue.

If you could post up a public repo on github that reproduces the problem we can help further.

Alternate options are posting the contents of `attr.coffee` to a gist or just pasting the line in `attr.coffee` related to `rendered` here.

**Comment by ManuelDeLeon** [comment]
Found it.

Stubs are not picked up from a coffeescript file (e.g. a2-package-stubs.coffee). here's a repo: https://github.com/ManuelDeLeon/jasmine-unit-rendered

It works if you rename 'a2-package-stubs.coffee' to 'a2-package-stubs.js' and change the contents accordingly:

Template = {
    attr: {}
};

While we're on the subject, is there a way to add all template stubs automagically or something? Kinda hard to use jasmine-unit with an existing project.

**Comment by alanning** [comment]
Hmm, interesting use case.  We should definitely support stubs in coffeescript files.

Re: the templates, we do actually auto-stub all the templates we find for you.  You can see the log messages like, "stubbing template: player" in the debug output.

But we get the templates from the HTML files (so we don't have to search all js, then all coffee, then all x, etc).  In this case you have a template `attr` which does not actually have a corresponding HTML template defined.

Not sure if we should try to support that or just note in the documentation that all templates must have an HTML part to be auto-stubbed.

In your use-case is it on-purpose or just something that you hadn't completed yet?

**Comment by SamHatoum** [comment]
Coffee stubs should be an easy add, I'll get on that #26

One way we could support  HTML files is for the launcher (main.js) which runs in context, to walk the Templates object and stub all templates there. This approach would make the above work I think. Thoughts @alanning ?

**Comment by alanning** [comment]
Yeah, that's true, we can do it from the launcher like we do packages.  That would mean that the template stubs have to be written to a file (like we do with packages, "a1-package-stubs.js").

Would handle this case but its also more complex.  Hmm...

**Comment by ManuelDeLeon** [comment]
You're right, you do pick up templates defined in html files. The reason why it didn't work for me in the first place is because I used .jade files. Any chance you guys can also parse jade files when you look for templates? Should I create a new issue?

**Comment by alanning** [comment]
Oh, jade.  Nice!  Yes, please create a new issue.  Also, please include an example of how it is defined in the jade file so we know what to search for when finding the templates.  

Currently we look for something like:

`<template="name"`

...in the HTML files
