### ISSUE TITLE
Getting error in console "ServiceConfiguration is not defined"

### ISSUE THREAD

**Issue by alanning** [xolvio/jasmine-unit#35]
// Migrated from xolvio/velocity#65 by @hkirk

Getting the error output below in meteor. Everything seems to work regardless of this error. Havn't added any other test than the sample.

I20140724-10:47:37.783(2)? Error loading app files ServiceConfiguration is not defined ReferenceError: ServiceConfiguration is not defined
Error loading app files ServiceConfiguration is not defined ReferenceError: ServiceConfiguration is not defined
I20140724-10:47:37.783(2)?   at Object.<anonymous> (/Users/henrik/Private/afrigter/server/accounts.js:5:1)
I20140724-10:47:37.784(2)?   at Module._compile (module.js:456:26)
I20140724-10:47:37.784(2)?   at Object.Module._extensions..js (module.js:474:10)
I20140724-10:47:37.784(2)?   at Module.load (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
I20140724-10:47:37.784(2)?   at Function.Module._load (module.js:312:12)
I20140724-10:47:37.784(2)?   at Module.require (module.js:364:17)
I20140724-10:47:37.785(2)?   at require (module.js:380:17)
I20140724-10:47:37.785(2)?   at loadFile (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/lib/file-loader.js:105:7)
I20140724-10:47:37.785(2)?   at Function.forEach (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/lodash/dist/lodash.js:3297:15)
I20140724-10:47:37.785(2)?   at Object.loadFiles (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/lib/file-loader.js:34:5)
I20140724-10:47:37.785(2)?   at Object.<anonymous> (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/lib/loader-helper.js:43:14)
I20140724-10:47:37.785(2)?   at Module._compile (module.js:456:26)
I20140724-10:47:37.791(2)?   at Object.Module._extensions..js (module.js:474:10)
I20140724-10:47:37.791(2)?   at Module.load (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
I20140724-10:47:37.791(2)?   at Function.Module._load (module.js:312:12)
I20140724-10:47:37.791(2)?   at Module.require (module.js:364:17)
I20140724-10:47:37.791(2)?   at require (module.js:380:17)
I20140724-10:47:37.791(2)?   at Object.jasmine.loadHelpersInFolder (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/index.js:64:20)
I20140724-10:47:37.791(2)?   at /Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/cli.js:221:13
I20140724-10:47:37.791(2)?   at Array.forEach (native)
I20140724-10:47:37.791(2)?   at Object.<anonymous> (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/cli.js:220:15)
I20140724-10:47:37.791(2)?   at Module._compile (module.js:456:26)
I20140724-10:47:37.792(2)?   at Object.Module._extensions..js (module.js:474:10)
I20140724-10:47:37.792(2)?   at Module.load (module.js:356:32)
I20140724-10:47:37.792(2)?   at Function.Module._load (module.js:312:12)
I20140724-10:47:37.792(2)?   at Function.Module.runMain (module.js:497:10)
I20140724-10:47:37.792(2)?   at startup (node.js:119:16)
I20140724-10:47:37.792(2)?   at node.js:906:3

**Comment by alanning** [comment]
@hkirk It looks like the file `/Users/henrik/Private/afrigter/server/accounts.js` is referencing an object `ServiceConfiguration` which has not been defined yet.  Probably a missing stub.

Can you post a bit of the relevant code from your `accounts.js` file, please?

Also, if you could run with full debugging turned on and post the results to a gist that would be helpful:

`$ DEBUG=1 VELOCITY_DEBUG=1 JASMINE_DEBUG=1 meteor`

**Comment by SamHatoum** [comment]
@alanning on a side note for jasmine-unit's exception handling, I wonder if we can do something clever here, like see when exceptions are happening at loading time of unit tests vs any same exceptions happening in the Meteor startup. So far, every exception seems to be a missing stub and is due to 'undefined'. If we don't detect an exception in the main meteor startup of anything being undefined, is it a 100% case that the error is a stubbing error? Therefore could we swallow the exception and report a stubbing error instead? This would be less intimidating to users and could even post info there and then letting users know where to go for stubbing help.

**Comment by alanning** [comment]
@samhatoum Yeah, that sounds good.  I don't know of a way to 100% detect stubbing errors but a low risk step we can take now is to check exceptions for "...is not defined" and suggest it is probably a stubbing issue with instructions on how to report it to the package-stubber project.

**Comment by SamHatoum** [comment]
yes, and I think removing the stack puke, perhaps dumping to a file instead would be a less intimidating experience

**Comment by hkirk** [comment]
You can get all over my server/account.sj file

ServiceConfiguration.configurations.remove({
    service: "facebook"
});

ServiceConfiguration.configurations.insert({
    service: "facebook",
    appId: "xxxxx",
    secret: "xxxx"
});

Output from debug:
loading a bunch og files
I20140724-16:39:23.576(2)? loading source file: /Users/henrik/Private/afrigter/server/accounts.js
I20140724-16:39:23.578(2)? Error loading app files ServiceConfiguration is not defined ReferenceError: ServiceConfiguration is not defined
I20140724-16:39:23.578(2)?   at Object.<anonymous> (/Users/henrik/Private/afrigter/server/accounts.js:5:1)
I20140724-16:39:23.579(2)?   at Module._compile (module.js:456:26)
I20140724-16:39:23.579(2)?   at Object.Module._extensions..js (module.js:474:10)
I20140724-16:39:23.579(2)?   at Module.load (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
I20140724-16:39:23.579(2)?   at Function.Module._load (module.js:312:12)
I20140724-16:39:23.579(2)?   at Module.require (module.js:364:17)
I20140724-16:39:23.579(2)?   at require (module.js:380:17)
I20140724-16:39:23.579(2)?   at loadFile (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/lib/file-loader.js:105:7)
I20140724-16:39:23.579(2)?   at Function.forEach (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/lodash/dist/lodash.js:3297:15)
I20140724-16:39:23.579(2)?   at Object.loadFiles (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/lib/file-loader.js:34:5)
I20140724-16:39:23.580(2)?   at Object.<anonymous> (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/lib/loader-helper.js:43:14)
I20140724-16:39:23.580(2)?   at Module._compile (module.js:456:26)
I20140724-16:39:23.580(2)?   at Object.Module._extensions..js (module.js:474:10)
I20140724-16:39:23.580(2)?   at Module.load (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
I20140724-16:39:23.580(2)?   at Function.Module._load (module.js:312:12)
I20140724-16:39:23.580(2)?   at Module.require (module.js:364:17)
I20140724-16:39:23.580(2)?   at require (module.js:380:17)
I20140724-16:39:23.580(2)?   at Object.jasmine.loadHelpersInFolder (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/index.js:64:20)
I20140724-16:39:23.580(2)?   at /Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/cli.js:221:13
I20140724-16:39:23.582(2)?   at Array.forEach (native)
I20140724-16:39:23.582(2)?   at Object.<anonymous> (/Users/henrik/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/cli.js:220:15)
I20140724-16:39:23.582(2)?   at Module._compile (module.js:456:26)
I20140724-16:39:23.582(2)?   at Object.Module._extensions..js (module.js:474:10)
I20140724-16:39:23.582(2)?   at Module.load (module.js:356:32)
I20140724-16:39:23.583(2)?   at Function.Module._load (module.js:312:12)
I20140724-16:39:23.583(2)?   at Function.Module.runMain (module.js:497:10)
I20140724-16:39:23.583(2)?   at startup (node.js:119:16)
I20140724-16:39:23.583(2)?   at node.js:906:3

Intellij also detects ServiceConfiguration as missing, but it doesn't produce any errors and facebook intergration seems to work fine

**Comment by ghost** [comment]
@alanning It's exported from the Meteor package: https://github.com/meteor/meteor/blob/release/0.8.2/packages/service-configuration/package.js
This package is a dependency of accounts-base that you usually add as a dependency to your app.

**Comment by alanning** [comment]
OK, since this is a regular part of accounts-base we should add it to [meteor-stubs](https://github.com/alanning/meteor-stubs/blob/master/index.js).

@hkirk To prevent the error from occurring you can add the stub yourself by adding it to your tests directory, for example, `tests/service-configuration-stub.js`.  If you do create a stub for it please submit a PR to the [meteor-stubs](https://github.com/alanning/meteor-stubs/blob/master/index.js) project!  That would be a big help!

**Comment by hkirk** [comment]
PR on your way. The code snippet works when set in tests/service-configuration.js.

**Comment by vishim** [comment]
Hi, you seem to be missing service-configuration package. Try adding it
meteor add service-configuration

**Comment by faridblaster** [comment]
@vishim  perfect

**Comment by juvyc** [comment]
I followed some suggestions in this thread but still not working, our development version is working fine but when we deploy it the errors appear.

Uncaught TypeError: Cannot read property 'easing' of undefined
Uncaught TypeError: Cannot read property 'ServiceConfiguration' of undefined

Any other possible fixes on this?

Thanks
