### ISSUE TITLE
Errors thrown by jasmine-unit

### ISSUE THREAD

**Issue by geekyme** [xolvio/jasmine-unit#37]
I get strange errors thrown by jasmine-unit after I installed velocity-quick-start onto my own simple meteor boilerplate. Note that the templates are written in Jade. 

To replicate my problem, try: 
1. git clone my boilerplate https://github.com/geekyme/next
2. mrt install
3. mrt add velocity-quick-start
4. meteor

There seem to be trouble calling the helpers on my templates (in jade) 

<pre>
loading source file: /Users/jayjamero/Desktop/shawn/meteor/miniprose/client/views/dynamic/items.js
I20140729-16:49:45.627(8)? Error loading app files Cannot call method 'helpers' of undefined TypeError: Cannot call method 'helpers' of undefined
</pre>

This is the trace of the debug log: 

<pre>
I20140729-16:49:45.523(8)? stubbing template: wrapLinks
I20140729-16:49:45.523(8)? loading stub file: a1-package-stubs.js
I20140729-16:49:45.534(8)?
I20140729-16:49:45.536(8)? GeometryComputationClass - 13 ms
I20140729-16:49:45.537(8)?     calculates surface area of a sphere correctly - 4 ms
I20140729-16:49:45.539(8)?     calculates surface area of a cube correctly - 0 ms
I20140729-16:49:45.541(8)?     calculates volume a sphere correctly - 0 ms
I20140729-16:49:45.544(8)?     calculates volume of a cube correctly - 0 ms
I20140729-16:49:45.544(8)?
I20140729-16:49:45.544(8)? Finished in 0.03 seconds
I20140729-16:49:45.545(8)? 4 tests, 4 assertions, 0 failures, 0 skipped
I20140729-16:49:45.545(8)?
I20140729-16:49:45.546(8)?
I20140729-16:49:45.610(8)? loading source file: /Users/jayjamero/Desktop/shawn/meteor/miniprose/client/lib/example.js
I20140729-16:49:45.612(8)? loading source file: /Users/jayjamero/Desktop/shawn/meteor/miniprose/common/lib/example.js
I20140729-16:49:45.615(8)? loading source file: /Users/jayjamero/Desktop/shawn/meteor/miniprose/client/views/components/example.js
I20140729-16:49:45.615(8)? loading source file: /Users/jayjamero/Desktop/shawn/meteor/miniprose/client/views/dynamic/items.js
I20140729-16:49:45.627(8)? Error loading app files Cannot call method 'helpers' of undefined TypeError: Cannot call method 'helpers' of undefined
I20140729-16:49:45.628(8)?   at Object.<anonymous> (/Users/jayjamero/Desktop/shawn/meteor/miniprose/client/views/dynamic/items.js:1:78)
I20140729-16:49:45.628(8)?   at Module._compile (module.js:456:26)
I20140729-16:49:45.628(8)?   at Object.Module._extensions..js (module.js:474:10)
I20140729-16:49:45.628(8)?   at Module.load (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
I20140729-16:49:45.628(8)?   at Function.Module._load (module.js:312:12)
I20140729-16:49:45.629(8)?   at Module.require (module.js:364:17)
I20140729-16:49:45.629(8)?   at require (module.js:380:17)
I20140729-16:49:45.629(8)?   at loadFile (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/lib/file-loader.js:105:7)
I20140729-16:49:45.629(8)?   at Function.forEach (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/lodash/dist/lodash.js:3297:15)
I20140729-16:49:45.629(8)?   at Object.loadFiles (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/lib/file-loader.js:34:5)
I20140729-16:49:45.630(8)?   at Object.<anonymous> (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/lib/loader-helper.js:43:14)
I20140729-16:49:45.630(8)?   at Module._compile (module.js:456:26)
I20140729-16:49:45.630(8)?   at Object.Module._extensions..js (module.js:474:10)
I20140729-16:49:45.630(8)?   at Module.load (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
I20140729-16:49:45.630(8)?   at Function.Module._load (module.js:312:12)
I20140729-16:49:45.630(8)?   at Module.require (module.js:364:17)
I20140729-16:49:45.631(8)?   at require (module.js:380:17)
I20140729-16:49:45.631(8)?   at Object.jasmine.loadHelpersInFolder (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/index.js:64:20)
I20140729-16:49:45.631(8)?   at /Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/cli.js:221:13
I20140729-16:49:45.631(8)?   at Array.forEach (native)
I20140729-16:49:45.631(8)?   at Object.<anonymous> (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/cli.js:220:15)
I20140729-16:49:45.631(8)?   at Module._compile (module.js:456:26)
I20140729-16:49:45.632(8)?   at Object.Module._extensions..js (module.js:474:10)
I20140729-16:49:45.632(8)?   at Module.load (module.js:356:32)
I20140729-16:49:45.632(8)?   at Function.Module._load (module.js:312:12)
I20140729-16:49:45.633(8)?   at Function.Module.runMain (module.js:497:10)
I20140729-16:49:45.633(8)?   at startup (node.js:119:16)
I20140729-16:49:45.634(8)?   at node.js:906:3
I20140729-16:49:45.634(8)?
I20140729-16:49:45.640(8)? patched JUnitXmlReporter.writeFile
I20140729-16:49:45.651(8)?
I20140729-16:49:45.651(8)? GeometryComputationClass - 6 ms
I20140729-16:49:45.651(8)?     calculates surface area of a sphere correctly - 3 ms
I20140729-16:49:45.652(8)?     calculates surface area of a cube correctly - 0 ms
I20140729-16:49:45.652(8)?     calculates volume a sphere correctly - 0 ms
I20140729-16:49:45.652(8)?     calculates volume of a cube correctly - 1 ms
I20140729-16:49:45.652(8)?
I20140729-16:49:45.653(8)? Finished in 0.009 seconds
I20140729-16:49:45.654(8)? 4 tests, 4 assertions, 0 failures, 0 skipped
I20140729-16:49:45.655(8)?
I20140729-16:49:45.655(8)?
I20140729-16:49:45.808(8)? loading source file: /Users/jayjamero/Desktop/shawn/meteor/miniprose/client/lib/example.js
I20140729-16:49:45.809(8)? loading source file: /Users/jayjamero/Desktop/shawn/meteor/miniprose/common/lib/example.js
I20140729-16:49:45.810(8)? loading source file: /Users/jayjamero/Desktop/shawn/meteor/miniprose/client/views/components/example.js
I20140729-16:49:45.811(8)? loading source file: /Users/jayjamero/Desktop/shawn/meteor/miniprose/client/views/dynamic/items.js
I20140729-16:49:45.816(8)? Error loading app files Cannot call method 'helpers' of undefined TypeError: Cannot call method 'helpers' of undefined
I20140729-16:49:45.817(8)?   at Object.<anonymous> (/Users/jayjamero/Desktop/shawn/meteor/miniprose/client/views/dynamic/items.js:1:78)
I20140729-16:49:45.817(8)?   at Module._compile (module.js:456:26)
I20140729-16:49:45.817(8)?   at Object.Module._extensions..js (module.js:474:10)
I20140729-16:49:45.817(8)?   at Module.load (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
I20140729-16:49:45.817(8)?   at Function.Module._load (module.js:312:12)
I20140729-16:49:45.818(8)?   at Module.require (module.js:364:17)
I20140729-16:49:45.818(8)?   at require (module.js:380:17)
I20140729-16:49:45.818(8)?   at loadFile (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/lib/file-loader.js:105:7)
I20140729-16:49:45.818(8)?   at Function.forEach (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/lodash/dist/lodash.js:3297:15)
I20140729-16:49:45.818(8)?   at Object.loadFiles (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/lib/file-loader.js:34:5)
I20140729-16:49:45.819(8)?   at Object.<anonymous> (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/lib/loader-helper.js:43:14)
I20140729-16:49:45.819(8)?   at Module._compile (module.js:456:26)
I20140729-16:49:45.819(8)?   at Object.Module._extensions..js (module.js:474:10)
I20140729-16:49:45.819(8)?   at Module.load (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
I20140729-16:49:45.819(8)?   at Function.Module._load (module.js:312:12)
I20140729-16:49:45.819(8)?   at Module.require (module.js:364:17)
I20140729-16:49:45.820(8)?   at require (module.js:380:17)
I20140729-16:49:45.820(8)?   at Object.jasmine.loadHelpersInFolder (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/index.js:64:20)
I20140729-16:49:45.820(8)?   at /Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/cli.js:221:13
I20140729-16:49:45.820(8)?   at Array.forEach (native)
I20140729-16:49:45.820(8)?   at Object.<anonymous> (/Users/jayjamero/.meteorite/packages/jasmine-unit/xolvio/jasmine-unit/885dde77a96390d0fd31b03756f837f482db2ef1/.npm/package/node_modules/jasmine-node-reporter-fix/lib/jasmine-node/cli.js:220:15)
I20140729-16:49:45.820(8)?   at Module._compile (module.js:456:26)
I20140729-16:49:45.821(8)?   at Object.Module._extensions..js (module.js:474:10)
I20140729-16:49:45.821(8)?   at Module.load (module.js:356:32)
I20140729-16:49:45.821(8)?   at Function.Module._load (module.js:312:12)
I20140729-16:49:45.821(8)?   at Function.Module.runMain (module.js:497:10)
I20140729-16:49:45.821(8)?   at startup (node.js:119:16)
I20140729-16:49:45.821(8)?   at node.js:906:3
I20140729-16:49:45.821(8)?
I20140729-16:49:45.826(8)? patched JUnitXmlReporter.writeFile
I20140729-16:49:45.835(8)?
I20140729-16:49:45.835(8)? GeometryComputationClass - 4 ms
I20140729-16:49:45.835(8)?     calculates surface area of a sphere correctly - 2 ms
I20140729-16:49:45.836(8)?     calculates surface area of a cube correctly - 0 ms
I20140729-16:49:45.836(8)?     calculates volume a sphere correctly - 1 ms
I20140729-16:49:45.836(8)?     calculates volume of a cube correctly - 0 ms
I20140729-16:49:45.836(8)?
I20140729-16:49:45.836(8)? Finished in 0.007 seconds
I20140729-16:49:45.837(8)? 4 tests, 4 assertions, 0 failures, 0 skipped
I20140729-16:49:45.837(8)?
I20140729-16:49:45.838(8)?
I20140729-16:49:57.971(8)? Mirror started { statusCode: 200, url: 'http://localhost:5000/', port: 5000 }

</pre>

**Comment by alanning** [comment]
There is a branch for Jade support, can you please have a try with that and see if it resolves the errors?

(Sorry, on mobile so no link)
