### ISSUE TITLE
Jasmine-unit and reactive-publish error

### ISSUE THREAD

**Issue by bitomule** [xolvio/jasmine-unit#42]
Hi guys, trying to use jasmine-unit again and I get this error:

```
ReferenceError: Deps is not defined
W20140829-12:32:55.442(0)? (STDERR)     at override.observeChanges (packages/reactive-    publish/lib/reactive-publish.coffee:18:11)
W20140829-12:32:55.443(0)? (STDERR)     at cursorProto.(anonymous function) [as observeChanges] (packages/kadira/lib/hijack/db.js:103)
W20140829-12:32:55.443(0)? (STDERR)     at Function.LocalCollection._observeFromObserveChanges (packages/minimongo/observe.js:176)
W20140829-12:32:55.444(0)? (STDERR)     at Cursor.observe (packages/mongo-livedata/mongo_driver.js:777)
W20140829-12:32:55.444(0)? (STDERR)     at cursorProto.(anonymous function) [as observe] (packages/kadira/lib/hijack/db.js:103)
W20140829-12:32:55.445(0)? (STDERR)     at Package (packages/jasmine-unit/main.js:201)
W20140829-12:32:55.446(0)? (STDERR)     at Package (packages/jasmine-unit/main.js:209)
W20140829-12:32:55.446(0)? (STDERR)     at /home/action/workspace/myapp/.meteor/local/build/programs/server/packages/jasmine-unit.js:235:4
W20140829-12:32:55.447(0)? (STDERR)     at /home/action/workspace/myapp/.meteor/local/build/programs/server/packages/jasmine-unit.js:242:3
W20140829-12:32:55.447(0)? (STDERR)     at /home/action/workspace/myapp/.meteor/local/build/programs/server/boot.js:161:10
```

Any idea on why this happens?

**Comment by alanning** [comment]
Hmm, that's weird.  Seems like the [Deps stub](https://github.com/alanning/meteor-stubs/blob/master/index.js#L265) wasn't loaded or something.

Can you run with full debugging and post the results in a gist, please?

`$ DEBUG=1 JASMINE_DEBUG=1 VELOCITY_DEBUG=1 meteor`

**Comment by bitomule** [comment]
Here's the full log running with debug. I think it's the same:

```
W20140829-14:59:48.794(0)? (STDERR) /home/action/.meteor/tools/cef2bcd356/lib/node_modules/fibers/future.js:173
W20140829-14:59:48.795(0)? (STDERR)                                             throw(ex);
W20140829-14:59:48.795(0)? (STDERR)                                                   ^
W20140829-14:59:48.830(0)? (STDERR) ReferenceError: Deps is not defined
W20140829-14:59:48.831(0)? (STDERR)     at override.observeChanges (packages/reactive-publish/lib/reactive-publish.coffee:18:11)
W20140829-14:59:48.831(0)? (STDERR)     at cursorProto.(anonymous function) [as observeChanges] (packages/kadira/lib/hijack/db.js:103)
W20140829-14:59:48.831(0)? (STDERR)     at Function.LocalCollection._observeFromObserveChanges (packages/minimongo/observe.js:176)
W20140829-14:59:48.831(0)? (STDERR)     at Cursor.observe (packages/mongo-livedata/mongo_driver.js:777)
W20140829-14:59:48.832(0)? (STDERR)     at cursorProto.(anonymous function) [as observe] (packages/kadira/lib/hijack/db.js:103)
W20140829-14:59:48.832(0)? (STDERR)     at Package (packages/jasmine-unit/main.js:201)
W20140829-14:59:48.833(0)? (STDERR)     at Package (packages/jasmine-unit/main.js:209)
W20140829-14:59:48.833(0)? (STDERR)     at /home/action/workspace/myapp/.meteor/local/build/programs/server/packages/jasmine-unit.js:235:4
W20140829-14:59:48.833(0)? (STDERR)     at /home/action/workspace/myapp/.meteor/local/build/programs/server/packages/jasmine-unit.js:242:3
W20140829-14:59:48.834(0)? (STDERR)     at /home/action/workspace/myapp/.meteor/local/build/programs/server/boot.js:161:10
=> Exited with code: 8
```

BTW, I'm running meteor 0.8.3.

**Comment by alanning** [comment]
Hmm, the full log should look something like the one you posted before: https://gist.github.com/bitomule/2fe7a1abfeb164e40ccc

With a bunch of PackageStubber and Template debugging info...

**Comment by bitomule** [comment]
And any idea why that log does't appear? I'm running it with the command you posted:

```
DEBUG=1 JASMINE_DEBUG=1 VELOCITY_DEBUG=1 meteor
```

**Comment by alanning** [comment]
If you remove the `reactive-publish` package do you see the full log then?

**Comment by bitomule** [comment]
I get one line more before the same crash:

```
Jasmine-Unit is loaded
```

**Comment by bitomule** [comment]
I'm running my app in nitrous.io, I've cloned it to my computer and now I'm loading it, hope I get the full log here.

**Comment by bitomule** [comment]
Nope, I get the same in my computer.

**Comment by bitomule** [comment]
Yeah, not sure how but I have the log:

https://gist.github.com/bitomule/c84e3a403740300f4d70

**Comment by bitomule** [comment]
Ok, I think all my problems are related to low memory. sorry about that.

**Comment by alanning** [comment]
No worries.  We've had memory issues running on nitrous.io ourselves when trying it out for pair programming sessions.
