### ISSUE TITLE
/velocityTestFiles/insert already defined when trying to upgrade velocity-example to 0.9.2

### ISSUE THREAD

**Issue by awatson1978** [xolvio/jasmine-unit#46]
Hi,
Upgraded [velocity-example to 0.9.2](https://github.com/meteor-velocity/velocity-example/tree/meteor-0.9.2) this evening, and the xolvio:jasmine-unit package produced the following error:

``` sh
W20140920-00:13:45.500(-4)? (STDERR) 
W20140920-00:13:45.502(-4)? (STDERR) /Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.31.v4jv95++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
W20140920-00:13:45.502(-4)? (STDERR)                        throw(ex);
W20140920-00:13:45.503(-4)? (STDERR)                              ^
W20140920-00:13:45.503(-4)? (STDERR) Error: A method named '/velocityTestFiles/insert' is already defined
W20140920-00:13:45.503(-4)? (STDERR)   at /Users/abigailwatson/Code/Meteor/velocity-example/.meteor/local/build/programs/server/packages/ddp.js:2264:15
W20140920-00:13:45.503(-4)? (STDERR)   at Function._.each._.forEach (/Users/abigailwatson/Code/Meteor/velocity-example/.meteor/local/build/programs/server/packages/underscore.js:147:22)
W20140920-00:13:45.503(-4)? (STDERR)   at [object Object]._.extend.methods (/Users/abigailwatson/Code/Meteor/velocity-example/.meteor/local/build/programs/server/packages/ddp.js:2262:7)
W20140920-00:13:45.503(-4)? (STDERR)   at [object Object].Mongo.Collection._defineMutationMethods (/Users/abigailwatson/Code/Meteor/velocity-example/.meteor/local/build/programs/server/packages/mongo.js:4007:24)
W20140920-00:13:45.504(-4)? (STDERR)   at new Mongo.Collection (/Users/abigailwatson/Code/Meteor/velocity-example/.meteor/local/build/programs/server/packages/mongo.js:3327:8)
W20140920-00:13:45.504(-4)? (STDERR)   at DEBUG (/Users/abigailwatson/Code/Meteor/velocity-example/.meteor/local/build/programs/server/packages/xolvio_velocity.js:28:21)
W20140920-00:13:45.504(-4)? (STDERR)   at /Users/abigailwatson/Code/Meteor/velocity-example/.meteor/local/build/programs/server/packages/xolvio_velocity.js:68:4
W20140920-00:13:45.504(-4)? (STDERR)   at /Users/abigailwatson/Code/Meteor/velocity-example/.meteor/local/build/programs/server/packages/xolvio_velocity.js:957:3
W20140920-00:13:45.505(-4)? (STDERR)   at /Users/abigailwatson/Code/Meteor/velocity-example/.meteor/local/build/programs/server/boot.js:161:10
W20140920-00:13:45.505(-4)? (STDERR)   at Array.forEach (native)
W20140920-00:13:45.505(-4)? (STDERR)   at Function._.each._.forEach (/Users/abigailwatson/.meteor/packages/meteor-tool/.1.0.31.v4jv95++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20140920-00:13:45.505(-4)? (STDERR)   at /Users/abigailwatson/Code/Meteor/velocity-example/.meteor/local/build/programs/server/boot.js:82:5
W20140920-00:13:45.505(-4)? (STDERR) 
```

**Comment by queso** [comment]
Did you leave old packages in the .meteor/packages file?

**Comment by awatson1978** [comment]
Only core packages.  Looks something like this:

``` sh
standard-app-packages
autopublish
insecure

mrt:momentjs
clinical:nightwatch
velocity:core
velocity:html-reporter
mike:mocha
sanjo:jasmine
#xolvio:jasmine-unit
```

**Comment by alanning** [comment]
The jasmine-unit package isn't compatible with the new package system so that should be removed.

But sanjo:jasmine now supports server-side unit tests in addition to the regular client side integration tests!
